\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Estudo de Caso 3: Planejamento e Análise de Experimentos},
            pdfauthor={Matheus Marzochi, Mayra Mota, Rafael Ramos e Victor Magalhães},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Estudo de Caso 3: Planejamento e Análise de Experimentos}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Matheus Marzochi, Mayra Mota, Rafael Ramos e Victor Magalhães}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{11 de Novembro de 2019}


\begin{document}
\maketitle

\hypertarget{resumo}{%
\subsection{Resumo}\label{resumo}}

O objetivo deste estudo de caso é investigar como modificações de
hiperparâmetros de um algoritmo de otimização baseado em evolução
diferencial influenciam em seu desempenho, em diferentes cenários de
execução. Os algoritmos serão testados a partir de funções de
Rosenbrock, de dimensões entre 2 e 150.

\hypertarget{papeis-desempenhados}{%
\subsection{Papéis Desempenhados}\label{papeis-desempenhados}}

A divisão de tarefas no grupo segue a descrição da \emph{Declaração de
Políticas de Equipe}. Estando aqui organizada da seguinte forma:

\begin{itemize}
\tightlist
\item
  Matheus: Verificador
\item
  Mayra: Monitora
\item
  Rafael: Coordenador
\item
  Victor: Revisor
\end{itemize}

\hypertarget{planejamento-do-experimento}{%
\subsection{Planejamento do
Experimento}\label{planejamento-do-experimento}}

\hypertarget{descricao-do-problema}{%
\subsubsection{Descrição do Problema}\label{descricao-do-problema}}

O problema analisado tem por objetivo comparar o desempenho de duas
configurações de um algoritmo de otimização baseada em evolução
diferencial, na resolução do problema de otimização da função de
Rosenbrock. As funções podem possuir dimensões que variam entre 2 e 150.
A hipótese nula é a de que o desempenho dos dois algoritmos permanece o
mesma independente da configuração, e a hipótese que está sendo testada
é a de que existe uma diferenção de desempenho entre elas.

Para avaliar o desempenho de cada um dos algoritmos, seus desempenhos
sob diferentes dimensões da função de Rosenbrook são levados em
consideração, a partir de testes pareados. Testes pareados constituem
uma parte de testes blocados, onde distribuições são comparadas caso a
caso, agrupadas em blocos, com o objetivo de diminuir efeitos que não
estejam relacionados com os parâmetros em teste. O valor de performance
\(y\) para cara algoritmo \(i\) em cada instância \(j\) é dado a partir
da fórmula (Montgomery and Runger 2012):

\[
y_{ij} = \mu + \tau_i + \beta_j + \epsilon_{ij}
\]

onde \(\mu\) corresponde à média geral de todas as amostras, \(\tau_i\)
corresponde o efeito do i-ésimo algoritmo, \(\beta_j\) representa , e
\(\epsilon_{ij}\) representa um erro randômico com média nula e
independentemente distribuídos, de variância \(\sigma^2\).

O que queremos testar é a equivalência dos parâmetros sob teste para
cada algoritmo, ou seja, \(y_i\). Seja \(y_i\) definido como:

\[
  y_i = \sum^{n}_{j = 1} y_{ij} \\
  \overline{y_i} = \frac{y_i}{n}
\]

onde \(n\) equivale ao total de instâncias (blocos). A hipótese nula é:

\[
H_0: y_1 = y_2 = ... = y_a
\]

onde a equivale ao total de algoritmos sendo comparados, o que no
problema em questão são 2. Como o que difere cada parâmetro \(y_i\) é o
valor da influência do algoritmo i, dizer que a hipótese nula é que os
parâmetros \(y_i\) são iguais equivale a dizer que

\[
H_0: \tau_1 = \tau_2 = ... = \tau_a = 0
\]

o que indica não haver influência do algoritmo nos parâmetros das
execuções, e a definição do mesmo passa a ser portanto apenas a média
global acrescida de um erro \(\epsilon_{ij}\). Isto equivale a dizer que
todas as observações foram retiradas de uma distribuição normal com
média \(\mu\) e variância \(\sigma^2\). A hipótese em teste, é:

\[
H_1: \tau_i = 0 
\]

para pelo menos algum valor de i.

Para este trabalho, deseja-se saber se existe alguma diferença no
desempenho médio do algoritmo quando carregado com diferentes
configurações. O parâmetro utilizado foi baseado na diferença do
desempenho médio das configurações 1 e 2, por tratar-se de uma análise
pareada. Se as duas configurações apresentarem o mesmo desempenho, a
diferença das médias de cada população amostrada será zero. Se uma
configuração tiver o desempenho superior, o valor não será nulo. Desta
forma, sendo \(\mu= \mu_1 - \mu_2\), o teste deve possuir as seguintes
hipóteses: \[
\begin{cases} H_0: \mu= 0 & \\ 
H_1: \mu\neq 0 \end{cases}
\]

\hypertarget{execucao-do-experimento}{%
\subsubsection{Execução do Experimento}\label{execucao-do-experimento}}

Como deseja-se avaliar o desempenho das duas configurações de algoritmos
sob diferentes dimensões de problema, serão realizados testes pareados.
Cada observação do teste corresponde a uma dimensão do problema de
Rosenbrock. Considerando as métricas para o teste estabelecidas
anteriormente, o número de instâncias para o teste pareado deverá ser,
no mínimo, 34 amostras, como o cálculo a seguir demonstra.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result <-}\StringTok{ }\KeywordTok{power.t.test}\NormalTok{(}\DataTypeTok{delta=}\FloatTok{0.5}\NormalTok{,}
             \DataTypeTok{sig.level=}\FloatTok{0.05}\NormalTok{,}
             \DataTypeTok{power=}\FloatTok{0.8}\NormalTok{,}
             \DataTypeTok{type=}\StringTok{'paired'}\NormalTok{,}
             \DataTypeTok{alternative=}\StringTok{'two.sided'}\NormalTok{)}
\KeywordTok{print}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      Paired t test power calculation 
## 
##               n = 33.3672
##           delta = 0.5
##              sd = 1
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*, sd is std.dev. of *differences* within pairs
\end{verbatim}

\hypertarget{coleta-dos-dados}{%
\subsection{Coleta dos Dados}\label{coleta-dos-dados}}

A princípio, não podemos assumir normalidade dos dados coletados, para
saber a quantidade de instâncias a ser utilizada, então, fizemos o
cálculo considerando o uso do teste de Wilcoxon (Lowry 2008), utilizando
a função \texttt{calc\_instances} (Campelo and Takahashi 2018).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Ncalc <-}\StringTok{ }\KeywordTok{calc_instances}\NormalTok{(}
    \DataTypeTok{power=}\FloatTok{0.8}\NormalTok{,}
    \DataTypeTok{d=}\FloatTok{0.5}\NormalTok{,}
    \DataTypeTok{sig.level=}\FloatTok{0.05}\NormalTok{,}
    \DataTypeTok{alternative.side=}\StringTok{'two.sided'}\NormalTok{,}
    \DataTypeTok{test=}\StringTok{'wilcoxon'}\NormalTok{,}
    \DataTypeTok{ncomparisons=}\DecValTok{1}
\NormalTok{)}
\KeywordTok{print}\NormalTok{(Ncalc}\OperatorTok{$}\NormalTok{ninstances)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 40
\end{verbatim}

O que nos indica o uso de, no mínimo, 45 instâncias. A partir de uma
rotina de coleta, geramos arquivos csv com os resultados das execuções
dos algoritmos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n_instancias <-}\StringTok{ }\DecValTok{45}

\NormalTok{dimensions <-}\StringTok{ }\KeywordTok{sample}\NormalTok{(}\KeywordTok{seq}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{150}\NormalTok{), n_instancias)}

\NormalTok{out_dim.conf1 =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{nrow =} \DecValTok{0}\NormalTok{))}
\KeywordTok{colnames}\NormalTok{(out_dim.conf1) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"dim"}\NormalTok{, }\StringTok{"best"}\NormalTok{)}
\NormalTok{out_dim.conf2 =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{nrow =} \DecValTok{0}\NormalTok{))}
\KeywordTok{colnames}\NormalTok{(out_dim.conf2) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"dim"}\NormalTok{, }\StringTok{"best"}\NormalTok{)}

\NormalTok{count.dim <-}\StringTok{ }\DecValTok{1}
\ControlFlowTok{for}\NormalTok{ (d }\ControlFlowTok{in}\NormalTok{ dimensions)\{}

\NormalTok{    dim <-}\StringTok{ }\KeywordTok{ceil}\NormalTok{(d)}
    
    \ControlFlowTok{for}\NormalTok{ (r }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{30}\NormalTok{) \{}
        
    
        \KeywordTok{cat}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}n}\StringTok{Building dimension "}\NormalTok{, dim)}
    
\NormalTok{        fn <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(X)\{}
            \ControlFlowTok{if}\NormalTok{(}\OperatorTok{!}\KeywordTok{is.matrix}\NormalTok{(X)) X <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(X, }\DataTypeTok{nrow =} \DecValTok{1}\NormalTok{) }
\NormalTok{            Y <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(X, }\DataTypeTok{MARGIN =} \DecValTok{1}\NormalTok{,}
                       \DataTypeTok{FUN =}\NormalTok{ smoof}\OperatorTok{::}\KeywordTok{makeRosenbrockFunction}\NormalTok{(}\DataTypeTok{dimensions =}\NormalTok{ dim))}
            \KeywordTok{return}\NormalTok{(Y)}
\NormalTok{        \}}
\NormalTok{        selpars <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{name =} \StringTok{"selection_standard"}\NormalTok{)}
\NormalTok{        stopcrit <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{names =} \StringTok{"stop_maxeval"}\NormalTok{, }\DataTypeTok{maxevals =} \DecValTok{5000}\OperatorTok{*}\NormalTok{dim, }\DataTypeTok{maxiter =} \DecValTok{100}\OperatorTok{*}\NormalTok{dim)}
\NormalTok{        probpars <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{name =} \StringTok{"fn"}\NormalTok{, }\DataTypeTok{xmin =} \KeywordTok{rep}\NormalTok{(}\OperatorTok{-}\DecValTok{5}\NormalTok{, dim), }\DataTypeTok{xmax =} \KeywordTok{rep}\NormalTok{(}\DecValTok{10}\NormalTok{, dim))}
\NormalTok{        popsize =}\StringTok{ }\DecValTok{5} \OperatorTok{*}\StringTok{ }\NormalTok{dim}
    
        \CommentTok{## Config 1}
\NormalTok{        recpars1 <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{name =} \StringTok{"recombination_arith"}\NormalTok{)}
\NormalTok{        mutpars1 <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{name =} \StringTok{"mutation_rand"}\NormalTok{, }\DataTypeTok{f =} \DecValTok{4}\NormalTok{)}
        \CommentTok{## Config 2}
\NormalTok{        recpars2 <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{name =} \StringTok{"recombination_bin"}\NormalTok{, }\DataTypeTok{cr =} \FloatTok{0.7}\NormalTok{)}
\NormalTok{        mutpars2 <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\DataTypeTok{name =} \StringTok{"mutation_best"}\NormalTok{, }\DataTypeTok{f =} \DecValTok{3}\NormalTok{)}
    
\NormalTok{        out <-}\StringTok{ }\KeywordTok{ExpDE}\NormalTok{(}\DataTypeTok{mutpars =}\NormalTok{ mutpars1,}
                     \DataTypeTok{recpars =}\NormalTok{ recpars1,}
                     \DataTypeTok{popsize =}\NormalTok{ popsize,}
                     \DataTypeTok{selpars =}\NormalTok{ selpars,}
                     \DataTypeTok{stopcrit =}\NormalTok{ stopcrit,}
                     \DataTypeTok{probpars =}\NormalTok{ probpars,}
                     \DataTypeTok{showpars =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{show.iters =} \StringTok{"dots"}\NormalTok{, }\DataTypeTok{showevery =} \DecValTok{20}\NormalTok{))}
\NormalTok{        de <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\StringTok{"dim"}\NormalTok{=dim, }\StringTok{"best"}\NormalTok{=out}\OperatorTok{$}\NormalTok{Fbest, }\StringTok{"repetition"}\NormalTok{=r)}
\NormalTok{        out_dim.conf1 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(out_dim.conf1,de, }\DataTypeTok{stringsAsFactors=}\OtherTok{FALSE}\NormalTok{)}
    
\NormalTok{        out <-}\StringTok{ }\KeywordTok{ExpDE}\NormalTok{(}\DataTypeTok{mutpars =}\NormalTok{ mutpars2,}
                     \DataTypeTok{recpars =}\NormalTok{ recpars2,}
                     \DataTypeTok{popsize =}\NormalTok{ popsize,}
                     \DataTypeTok{selpars =}\NormalTok{ selpars,}
                     \DataTypeTok{stopcrit =}\NormalTok{ stopcrit,}
                     \DataTypeTok{probpars =}\NormalTok{ probpars,}
                     \DataTypeTok{showpars =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{show.iters =} \StringTok{"dots"}\NormalTok{, }\DataTypeTok{showevery =} \DecValTok{20}\NormalTok{))}
\NormalTok{        de <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\StringTok{"dim"}\NormalTok{=dim, }\StringTok{"best"}\NormalTok{=out}\OperatorTok{$}\NormalTok{Fbest, }\StringTok{"repetition"}\NormalTok{=r)}
\NormalTok{        out_dim.conf2 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(out_dim.conf2,de, }\DataTypeTok{stringsAsFactors=}\OtherTok{FALSE}\NormalTok{)}
    
\NormalTok{    \}}

\NormalTok{    count.dim <-}\StringTok{ }\NormalTok{count.dim }\OperatorTok{+}\StringTok{ }\DecValTok{1}
\NormalTok{\}}

\KeywordTok{write.csv}\NormalTok{(out_dim.conf1, }\StringTok{'conf_1.csv'}\NormalTok{, }\DataTypeTok{row.names=}\OtherTok{FALSE}\NormalTok{)}
\KeywordTok{write.csv}\NormalTok{(out_dim.conf2, }\StringTok{'conf_2.csv'}\NormalTok{, }\DataTypeTok{row.names=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Ao final, temos um conjunto com 45 instâncias correspondentes a ordens
do algoritmo de Rosenbrock, com 30 amostras em cada um.

\hypertarget{analise-exploratoria-dos-dados}{%
\subsection{Análise Exploratória dos
Dados}\label{analise-exploratoria-dos-dados}}

Avaliando as amostras contidas em cada instância, uma análise de
normalidade foi realizada:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{conf_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\DataTypeTok{file=}\StringTok{'conf_1.csv'}\NormalTok{, }\DataTypeTok{sep=}\StringTok{','}\NormalTok{)}
\NormalTok{conf_}\DecValTok{2}\NormalTok{<-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\DataTypeTok{file=}\StringTok{'conf_2.csv'}\NormalTok{, }\DataTypeTok{sep=}\StringTok{','}\NormalTok{)}

\NormalTok{dataConf1 <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{unlist}\NormalTok{(conf_}\DecValTok{1}\NormalTok{[,}\DecValTok{2}\NormalTok{])),}\DataTypeTok{nrow=}\KeywordTok{nrow}\NormalTok{(conf_}\DecValTok{1}\NormalTok{))}
\NormalTok{dataConf2 <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{unlist}\NormalTok{(conf_}\DecValTok{2}\NormalTok{[,}\DecValTok{2}\NormalTok{])),}\DataTypeTok{nrow=}\KeywordTok{nrow}\NormalTok{(conf_}\DecValTok{2}\NormalTok{))}

\NormalTok{difs <-}\StringTok{ }\KeywordTok{c}\NormalTok{()}
\NormalTok{all_conf_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\KeywordTok{c}\NormalTok{()}
\NormalTok{all_conf_}\DecValTok{2}\NormalTok{ <-}\StringTok{ }\KeywordTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (i  }\ControlFlowTok{in} \KeywordTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, }\KeywordTok{nrow}\NormalTok{(dataConf1), }\DecValTok{10}\NormalTok{)) \{}
    
\NormalTok{    samples1 <-}\StringTok{ }\KeywordTok{as.vector}\NormalTok{(dataConf1[i}\OperatorTok{:}\NormalTok{(i}\OperatorTok{+}\DecValTok{9}\NormalTok{),])}
\NormalTok{    samples2 <-}\StringTok{ }\KeywordTok{as.vector}\NormalTok{(dataConf2[i}\OperatorTok{:}\NormalTok{(i}\OperatorTok{+}\DecValTok{9}\NormalTok{),])}
\NormalTok{    all_conf_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\KeywordTok{c}\NormalTok{(all_conf_}\DecValTok{1}\NormalTok{, }\KeywordTok{mean}\NormalTok{(samples1))}
\NormalTok{    all_conf_}\DecValTok{2}\NormalTok{ <-}\StringTok{ }\KeywordTok{c}\NormalTok{(all_conf_}\DecValTok{2}\NormalTok{, }\KeywordTok{mean}\NormalTok{(samples2))}
\NormalTok{    dif <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(samples1) }\OperatorTok{-}\StringTok{ }\KeywordTok{mean}\NormalTok{(samples2)}
\NormalTok{    difs <-}\StringTok{ }\KeywordTok{c}\NormalTok{(difs, dif)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  difs
## W = 0.92502, p-value = 0.006281
\end{verbatim}

\begin{figure}[H]

{\centering \includegraphics{report_ec3_files/figure-latex/plot-1} 

}

\caption{Q-Q plot.}\label{fig:plot}
\end{figure}

\begin{verbatim}
## [1] 45 44
\end{verbatim}

De acordo com o teste de Shapiro-Wilk, o p-valor para a diferença foi de
\(0.006\), abaixo da incerteza de 0.05, o que é um indício de que a
distribuição dos dados não é normal.

\begin{figure}[H]

{\centering \includegraphics{report_ec3_files/figure-latex/boxplot-1} 

}

\caption{Boxplot para as diferenças das médias.}\label{fig:boxplot}
\end{figure}

O boxplot para as diferenças, como pode ser visto a seguir, mostra que
existe uma assimetria nos dados, o que corrobora com a hipótese de
não-normalidade. A partir da análise do diagrama, nota-se que os valores
são negativos. Assim, essa disposição pode levar à conclusão da
existência de uma diferença de desempenho entre as duas configurações.
Entretanto, não é suficiente para inferir com confiança sobre a
população.

\hypertarget{teste-de-hipotese}{%
\subsubsection{Teste de Hipótese}\label{teste-de-hipotese}}

Como visto, podemos refutar a hipótese nula de que os dados não vieram
de uma distribuição normal. Pode-se, portanto, realizar um teste pareado
com as médias dos dados obtidos para cada instância, usando o teste de
Wilcoxon (Lowry 2008).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result <-}\StringTok{ }\KeywordTok{wilcox.test}\NormalTok{(difs, }\DataTypeTok{alternative=}\StringTok{'two.sided'}\NormalTok{, }\DataTypeTok{conf.level=}\FloatTok{0.95}\NormalTok{, }\DataTypeTok{conf.int=}\NormalTok{T)}
\KeywordTok{print}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Wilcoxon signed rank test
## 
## data:  difs
## V = 0, p-value = 5.684e-14
## alternative hypothesis: true location is not equal to 0
## 95 percent confidence interval:
##  -5993713 -3620723
## sample estimates:
## (pseudo)median 
##       -4867810
\end{verbatim}

\hypertarget{estimacao-do-tamanho-de-efeito-e-intervalo-de-confianca}{%
\subsubsection{Estimação do tamanho de efeito e intervalo de
confiança}\label{estimacao-do-tamanho-de-efeito-e-intervalo-de-confianca}}

O intervalo de confiança (intervalo com probabilidade de 95\% de conter
o valor verdadeiro do parâmetro da população), por sua vez, foi obtido
diretamente do teste de Wilcoxon. Os resultados obtidos pelo teste
foram:

\begin{itemize}
\tightlist
\item
  Graus de Liberdade = 44
\item
  p-valor = 5.684 e-14
\item
  Intervalo de confiança = -5993713 a -3620723
\item
  Tamanho de efeito é -1.12.
\end{itemize}

O cálculo do tamanho de efeito é calculado de acordo com o trecho de
código abaixo:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z<-}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(result}\OperatorTok{$}\NormalTok{p.value}\OperatorTok{/}\DecValTok{2}\NormalTok{)}
\NormalTok{eff <-}\StringTok{ }\NormalTok{z}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{45}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'Effect Size'}\NormalTok{, eff))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Effect Size -1.12029320661378"
\end{verbatim}

O tamanho de efeito obtido foi -1.12. Esse valor indica uma perfeita
correlação negativa entre as duas configurações do algoritmo,
significando que a diferença entre os dois grupos é maior do que um
desvio padrão. Pode-se entender que quanto maior o tamanho do efeito,
maior é o impacto que a variável central do experimento está causando e
mais importante se torna o fato dela ter uma contribuição para a questão
analisada (Lindenau and Guimarães 2012).

Considerando o p-valor do teste pareado de Wilcoxon, temos que as
amostras da configuração 1 e 2 demonstraram diferença no desempenho dos
algoritmos. Assim podemos refutar nossa hipótese nula de que a diferença
das médias é igual a zero.

\hypertarget{discussao-para-melhoria-do-experimento}{%
\subsubsection{Discussão para Melhoria do
Experimento}\label{discussao-para-melhoria-do-experimento}}

Para uma melhoria de resultados, propõe-se o uso da herística citada em
(Campelo and Takahashi 2018). Porém esse método exigiria uma custo
computacional muito alto, mostrando-se inviável para o equipamento
utilizado para geração dos dados analisados no presente relátorio.

\hypertarget{conclusoes}{%
\subsection{Conclusões}\label{conclusoes}}

A principal conclusão que podemos tirar a respeito deste teste é que a
configuração 1 possui melhor desempenho que a configuração 2, vista no
boxplot anteriormente, uma vez que a distribuição dos dados entre a
diferença das médias(Configuração2-Configuração1) é negativa. Tal
conclusão apresentou uma confiança de 95\%.

\hypertarget{referencias}{%
\subsection*{Referências}\label{referencias}}
\addcontentsline{toc}{subsection}{Referências}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-Campelo}{}%
Campelo, Felipe, and Fernanda Takahashi. 2018. ``Sample Size Estimation
for Power and Accuracy in the Experimental Comparison of Algorithms.''

\leavevmode\hypertarget{ref-Lindenau}{}%
Lindenau, Luciano Santos Pinto, and Juliana Dal-Ri Guimarães. 2012.
``Calculando O Tamanho de Efeito No Spss.''

\leavevmode\hypertarget{ref-Wilcox}{}%
Lowry, Richard. 2008. \emph{Concepts \& Applications of Inferential
Statistics}.

\leavevmode\hypertarget{ref-Montgomery2012}{}%
Montgomery, Douglas, and George Runger. 2012. \emph{Estatística Aplicada
E Probabilidade Para Engenheiros}. LTC.


\end{document}
